// tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#191c1d",
        "surface-bright": "#f8f9fa",
        "inverse-primary": "#c6c6c6",
        "primary": "#000000",
        "on-surface": "#191c1d",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-secondary-fixed-variant": "#4d3800",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed": "#5e5e5e",
        "surface-container": "#edeeef",
        "tertiary": "#3b3b3b",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#474747",
        "surface": "#f8f9fa",
        "on-tertiary": "#e2e2e2",
        "error": "#ba1a1a",
        "primary-container": "#3b3b3b",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "on-secondary-fixed": "#261a00",
        "on-primary": "#e2e2e2",
        "on-error": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "on-secondary-container": "#261a00",
        "outline-variant": "#c6c6c6",
        "on-primary-fixed-variant": "#e2e2e2",
        "secondary": "#785900",
        "secondary-fixed-dim": "#d8a300",
        "on-tertiary-fixed": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "secondary-container": "#ffce5d",
        "primary-fixed": "#5e5e5e",
        "surface-tint": "#5e5e5e",
        "secondary-fixed": "#fabd00",
        "outline": "#777777",
        "on-surface-variant": "#474747",
        "background": "#f8f9fa",
        "tertiary-container": "#747474",
        "inverse-surface": "#2e3132",
        "surface-dim": "#d9dadb",
        "tertiary-fixed-dim": "#474747",
        "on-error-container": "#410002",
        main: 'var(--main)',
        overlay: 'var(--overlay)',
        bg: 'var(--bg)',
        bw: 'var(--bw)',
        blank: 'var(--blank)',
        text: 'var(--text)',
        mtext: 'var(--mtext)',
        border: 'var(--border)',
        ring: 'var(--ring)',
        ringOffset: 'var(--ring-offset)',
        secondaryBlack: '#212121', 
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "playfair": ['"Playfair Display"', 'serif'],
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem",
        "base": "5px"
      },
      boxShadow: {
        shadow: 'var(--shadow)'
      },
      translate: {
        boxShadowX: '4px',
        boxShadowY: '4px',
        reverseBoxShadowX: '-4px',
        reverseBoxShadowY: '-4px',
      },
      fontWeight: {
        base: '500',
        heading: '700',
      },
    },
  },
  plugins: [],
}