apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_nyZ4RETlbLm3@ep-polished-queen-a84ghl9a-pooler.eastus2.azure.neon.tech/blog?sslmode=require"
  REDIS_URL: "redis://redis:6379"
  EMAIL_USER: "abhasbehera560@gmail.com"
  EMAIL_PASS: "ygpdbxlirnuomluo"
  CLERK_SECRET_KEY: "sk_test_DPpAGH2ndIV5D2LtLvG66DOyQn4WGmqWWfCWDBFODt"
  CLERK_PUBLISHABLE_KEY: "pk_test_aW52aXRpbmctd2hpcHBldC0zNi5jbGVyay5hY2NvdW50cy5kZXYk"
  CLERK_API_KEY: "sk_test_DPpAGH2ndIV5D2LtLvG66DOyQn4WGmqWWfCWDBFODt"
  PORT: "3000"
